# -*- coding: utf-8 -*-
"""vehicle_registry.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1toElZyef3aLvEsjekZ1mPM3PfWAGnUiK
"""

import hashlib
import json
import os
import sys
import getpass
from typing import Dict
from cryptography.hazmat.primitives.asymmetric import rsa, padding
from cryptography.hazmat.primitives import serialization, hashes
from cryptography.hazmat.backends import default_backend

VEHICLE_DB_FILE = 'vehicle_registry.json'
PRIVATE_KEY_FILE = 'private_key.pem'
PUBLIC_KEY_FILE = 'public_key.pem'


def sha256_hash(message: str) -> str:
    """Return the SHA-256 hex digest of message."""
    h = hashlib.sha256()
    h.update(message.encode('utf-8'))
    return h.hexdigest()


def generate_and_save_rsa_keys(key_size: int = 2048) -> None:
    """Generate RSA key pair and save PEM files."""
    private_key = rsa.generate_private_key(public_exponent=65537, key_size=key_size, backend=default_backend())
    public_key = private_key.public_key()

    priv_pem = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption()
    )
    with open(PRIVATE_KEY_FILE, 'wb') as f:
        f.write(priv_pem)

    pub_pem = public_key.public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo
    )
    with open(PUBLIC_KEY_FILE, 'wb') as f:
        f.write(pub_pem)

    print(f"Keys generated and saved to '{PRIVATE_KEY_FILE}' and '{PUBLIC_KEY_FILE}'.")


def load_private_key():
    if not os.path.exists(PRIVATE_KEY_FILE):
        print("Private key not found. Generate keys first.")
        return None
    with open(PRIVATE_KEY_FILE, 'rb') as f:
        data = f.read()
    return serialization.load_pem_private_key(data, password=None, backend=default_backend())


def load_public_key():
    if not os.path.exists(PUBLIC_KEY_FILE):
        print("Public key not found. Generate keys first.")
        return None
    with open(PUBLIC_KEY_FILE, 'rb') as f:
        data = f.read()
    return serialization.load_pem_public_key(data, backend=default_backend())


def sign_message(message: str) -> bytes:
    """Sign a message with the private key and return signature bytes."""
    private_key = load_private_key()
    if private_key is None:
        return None
    signature = private_key.sign(
        message.encode('utf-8'),
        padding.PSS(mgf=padding.MGF1(hashes.SHA256()), salt_length=padding.PSS.MAX_LENGTH),
        hashes.SHA256()
    )
    return signature


def verify_signature(message: str, signature: bytes) -> bool:
    public_key = load_public_key()
    if public_key is None:
        return False
    try:
        public_key.verify(
            signature,
            message.encode('utf-8'),
            padding.PSS(mgf=padding.MGF1(hashes.SHA256()), salt_length=padding.PSS.MAX_LENGTH),
            hashes.SHA256()
        )
        return True
    except Exception:
        return False


def load_registry() -> Dict[str, Dict]:
    if not os.path.exists(VEHICLE_DB_FILE):
        return {}
    with open(VEHICLE_DB_FILE, 'r', encoding='utf-8') as f:
        try:
            return json.load(f)
        except Exception:
            print("Warning: vehicle registry file corrupted. Starting fresh.")
            return {}


def save_registry(registry: Dict[str, Dict]) -> None:
    with open(VEHICLE_DB_FILE, 'w', encoding='utf-8') as f:
        json.dump(registry, f, indent=2)


def register_vehicle():
    print('\n--- Register Vehicle ---')
    plate = input('Number Plate (unique): ').strip().upper()
    if not plate:
        print('Number Plate cannot be empty.')
        return
    registry = load_registry()
    if plate in registry:
        print(f"Error: Number Plate '{plate}' is already registered (duplicates not allowed).")
        return
    owner = input('Owner Name: ').strip()
    model = input('Model: ').strip()
    if not owner or not model:
        print('Owner and Model cannot be empty.')
        return
    registry[plate] = {'owner': owner, 'model': model}
    save_registry(registry)
    print(f"Vehicle {plate} registered successfully.")


def get_vehicle():
    print('\n--- Retrieve Vehicle ---')
    plate = input('Enter Number Plate: ').strip().upper()
    if not plate:
        print('Number Plate cannot be empty.')
        return
    registry = load_registry()
    if plate not in registry:
        print(f"No vehicle found for Number Plate '{plate}'.")
        return
    info = registry[plate]
    print(f"Number Plate: {plate}\nOwner: {info['owner']}\nModel: {info['model']}")


def print_menu():
    print('\n===== Cryptography & Vehicle Registry =====')
    print('1. SHA-256 Hash a message')
    print('2. Generate RSA key pair (save to files)')
    print('3. Sign a message (using private key)')
    print('4. Verify signature (using public key)')
    print('5. Register Vehicle')
    print('6. Retrieve Vehicle by Number Plate')
    print('7. Show stored keys & registry status')
    print('8. Exit')


def show_status():
    print('\n--- Status ---')
    print('Private key file:' , 'FOUND' if os.path.exists(PRIVATE_KEY_FILE) else 'MISSING')
    print('Public key file:' , 'FOUND' if os.path.exists(PUBLIC_KEY_FILE) else 'MISSING')
    reg = load_registry()
    print(f"Vehicles registered: {len(reg)}")


def main_loop():
    print('Welcome — Cryptography & Vehicle Registry App')
    while True:
        print_menu()
        choice = input('Choose an option (1-8): ').strip()
        if choice == '1':
            msg = input('\nEnter message to hash: ')
            print('SHA-256:', sha256_hash(msg))
        elif choice == '2':
            print('\nGenerating RSA key pair (2048 bits)...')
            generate_and_save_rsa_keys()
        elif choice == '3':
            msg = input('\nEnter message to sign: ')
            sig = sign_message(msg)
            if sig is None:
                print('Signing failed (private key missing).')
            else:
                print('\nSignature (hex):')
                print(sig.hex())
                save_opt = input('Save signature to file? (y/N): ').strip().lower()
                if save_opt == 'y':
                    fname = input('Enter filename to save signature (e.g. sig.bin): ').strip()
                    if fname:
                        with open(fname, 'wb') as f:
                            f.write(sig)
                        print(f'Signature saved to {fname}')
        elif choice == '4':
            msg = input('\nEnter original message: ')
            sig_in = input('Enter signature hex (or filename to load): ').strip()
            signature = None
            if os.path.exists(sig_in):
                with open(sig_in, 'rb') as f:
                    signature = f.read()
            else:
                try:
                    signature = bytes.fromhex(sig_in)
                except Exception:
                    print('Invalid signature input. Provide hex string or path to signature file.')
                    signature = None
            if signature is None:
                continue
            ok = verify_signature(msg, signature)
            print('Signature valid.' if ok else 'Signature INVALID!')
        elif choice == '5':
            register_vehicle()
        elif choice == '6':
            get_vehicle()
        elif choice == '7':
            show_status()
        elif choice == '8':
            print('Goodbye!')
            break
        else:
            print('Invalid choice. Enter a number between 1 and 8.')

if __name__ == '__main__':
    try:
        main_loop()
    except KeyboardInterrupt:
        print('\nInterrupted. Exiting.')
        sys.exit(0)